chat/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :conversations, only: [:create, :delete] do
    member do
      post :close
      delete :destroy
    end
    resources :messages, only: [:create]	
   end
  
end

chat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

chat/app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

chat/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

chat/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

chat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?


	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :is_admin])
		devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :is_admin])
	end
end

chat/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    
    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])

    session[:conversations].delete(@conversation.id)

    respond_to do |format|
      format.js
    end
  end

  def destroy
      @conversation = Conversation.find(params[:id])
      @conversation.destroy
      redirect_to root_path
  end
  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
  

  


end

chat/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 # .find(session[:conversations])

    @allConversations = Conversation.all
  end
end

chat/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

chat/app/helpers/application_helper.rb
module ApplicationHelper
end

chat/app/helpers/conversations_helper.rb
module ConversationsHelper
end

chat/app/helpers/home_helper.rb
module HomeHelper
end

chat/app/helpers/messages_helper.rb
module MessagesHelper
end

chat/app/views/conversations/_conversation.html.erb
<li class="col-md-4 conversation">
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= conversation.opposed_user(user).email %>
      <%= link_to image_tag("close.png"), close_conversation_path(conversation), class: "pull-right message-icon", remote: true, method: :post %>

      <%= link_to image_tag("expand.png"), '', class: 'pull-right toggle-window message-icon' %>
    </div>



    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <%= form_for [conversation, conversation.messages.new], remote: true do |f| %>
        <%= f.hidden_field :user_id, value: user.id %>
        <%= f.text_area :body, class: "form-control" %>
        <%= f.submit "Send", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</li>

chat/app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

chat/app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

chat/app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

chat/app/views/home/_messages.html.erb
<li>
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>

chat/app/views/home/index.html.erb
<div class="row all-content">

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <!-- <div> -->
          <div class="panel-title">
            <div class="dropdown btn">
              <img src="config.png" class="short-icon dropdown-toggle" data-toggle="dropdown">
              <!-- <ul class="dropdown-menu"> -->
                  <% if user_signed_in? %>
                    <!-- <div class="navbar-header">
                      <p class="navbar-brand"> Logged in as <strong>current_user.email</strong></p>
                    </div> -->


                    <ul class="dropdown-menu">
                      <% if current_user.is_admin? %>
                        <li data-toggle="modal", data-target="#exampleModalLong">All Conversations</li>
                      <% end %>
                        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
                      </ul>
                  <% else %>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Sign up", new_user_registration_path %> |</li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                     </ul>
                  <% end %>
              <!-- </ul> -->
            </div>
            <div class="users-title">Contacts</div>
          </div>
        <!-- </div> -->
        <!-- <div> -->
        <!-- </div> -->
      </div>
      <div class="panel-body">
        <div class="list-group">
          <% @users.each do |user| %>
          <%= link_to image_tag("user.png") + user.email, conversations_path(user_id: user), :class=>"list-group-item user-item", remote: true, method: :post %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
      <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Conversations</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <table class="table">
          <thead>
            <tr>
              <th scope="col">Sender</th>
              <th scope="col">Receiver</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @allConversations.each do |conversation| %>
              <tr>
                <td><%= conversation.sender.email %></td>
                <td><%= conversation.recipient.email %></td>
                <td><%= link_to '(Delete)', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>  
        </table>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>

chat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
</body>
</html>

chat/app/views/messages/_message.html.erb
<li class="message">
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>

chat/app/views/messages/create.js.erb
var conversation = $('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.messages-list').find('ul').append("<%= j(render 'messages/message', message: @message, user: current_user) %>");
conversation.find('textarea').val('');